language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t naveed019/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true naveed019/react-test npm run test

after_success:
  - docker build -t naveed019/multi-client ./client
  - docker build -t naveed019/multi-nginx ./nginx
  - docker build -t naveed019/multi-server ./server
  - docker build -t naveed019/multi-worker ./worker
  - echo "DOCKER_PASSWORD" | docker login docker.io -u "$DOCKER_ID" --password-stdin
  - docker push naveed019/multi-client
  - docker push naveed019/multi-nginx
  - docker push naveed019/multi-worker
  - docker push naveed019/multi-server
    
deploy: 
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-293794245415
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY  
  secret_access_key:
    secure: $AWS_SECRET_KEY
   